export const CHANGE_TITLE='CHANGE_TITLE';
export const SET_IS_LOGGED_IN='SET_IS_LOGGED_IN';
export const SET_USER='SET_USER';
export const SEARCH_VIDEOS_SUCCESS='SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAILURE='SEARCH_VIDEOS_FAILURE';
export const SEARCH_VIDEOS_STARTED='SEARCH_VIDEOS_STARTED';
export const SET_QUERY='SET_QUERY';
