export const CHANGE_TITLE='CHANGE_TITLE';
export const SET_IS_LOGGED_IN='SET_IS_LOGGED_IN';
export const SET_USER='SET_USER';
export const SEARCH_VIDEOS_SUCCESS='SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAILURE='SEARCH_VIDEOS_FAILURE';
export const SEARCH_VIDEOS_STARTED='SEARCH_VIDEOS_STARTED';
export const SET_SEARCH_QUERY='SET_SEARCH_QUERY';
export const SET_FAVORITES='SET_FAVORITES';
export const SET_SAVED_FAVORITES='SET_SAVED_FAVORITES';
export const DELETE_FAVORITE='DELETE_FAVORITE';
export const EDIT_FAVORITE='EDIT_FAVORITE';

export const SEARCH_VIDEOS_STATS_SUCCESS='SEARCH_VIDEOS_STATS_SUCCESS';
export const SEARCH_VIDEOS_STATS_FAILURE='SEARCH_VIDEOS_STATS_FAILURE';
export const SEARCH_VIDEOS_STATS_STARTED='SEARCH_VIDEOS_STATS_STARTED';
export const SRH_LOGOUT='SRH_LOGOUT';
